/*
Copyright © 2023 Gypsophlia <710852553@qq.com>
Generated by cobra-cli
*/
package cmd

import (
	"fmt"

	"goto/utils"

	"github.com/spf13/cobra"
)

// listCmd represents the list command
var listCmd = &cobra.Command{
	Use:   "list",
	Short: "show the list of tasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		fmt.Println("list called")
		tasks, err := utils.ReadFile(dbFile)
		if err == nil {
			fmt.Println(tasks)
		}
		return err
	},
}

func init() {
	rootCmd.AddCommand(listCmd)
}
