/*
Copyright © 2023 Gypsophlia <710852553@qq.com>
Generated by cobra-cli
*/
package cmd

import (
	"fmt"
	"strings"

	"goto/utils"
	"goto/utils/log"

	"github.com/spf13/cobra"
)

// listCmd represents the list command
var listCmd = &cobra.Command{
	Use:   "list",
	Short: "show the list of tasks",
	RunE: func(cmd *cobra.Command, args []string) error {
		tasks, err := utils.ReadFile(dbFile)
		if err == nil {
			for i := 0; i < len(tasks); i++ {
				task := tasks[i]
				log.Info("Name: %s\n", task.Name)
				fmt.Printf("Alias: %s\n", strings.Join(task.Alias, " "))
				fmt.Printf("Command: %s\n", task.Command)
			}
		}
		return err
	},
}

func init() {
	rootCmd.AddCommand(listCmd)
}
