/*
Copyright © 2023 Gypsophlia <710852553@qq.com>
Generated by cobra-cli
*/
package cmd

import (
	"fmt"
	"goto/utils"
	"goto/utils/log"
	"os"
	"os/exec"
	"runtime"

	"github.com/spf13/cobra"
)

// runCmd represents the run command
var runCmd = &cobra.Command{
	Use:   "run",
	Short: "run the command by name",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		tasks, err := utils.ReadFile(dbFile)
		if err != nil {
			return err
		}

		// check if name exists
		index := utils.FindIndex(args[0], tasks)
		if index == -1 {
			return fmt.Errorf("the name doesn't exists")
		}

		// Run command
		var exe *exec.Cmd
		command := tasks[index].Command
		log.Info("Start running command: %s", command)

		switch runtime.GOOS {
		case "linux":
			exe = exec.Command("/bin/sh", "-c", command)
		case "windows":
			exe = exec.Command("cmd", "/c", command)
		}
		exe.Stdin = os.Stdin
		exe.Stderr = os.Stderr
		exe.Stdout = os.Stdout
		err = exe.Run()

		log.Info("Finish running command")
		return err
	},
}

func init() {
	rootCmd.AddCommand(runCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// runCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	// runCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
